### ISSUE TITLE
ngx-scroll event not working

### ISSUE THREAD

**Issue by Shreyanshupare** [anasAsh/ngx-scroll-event#10]
in my application, I have changed in TS, HTML and CSS file. But it is not calling Handle scroll event.
I am using 1.8 version of ngx-scroll.
Any different configuration also needed? My application code is in angular 5.
and also bottom offset and top offset is showing error like:-
for this <div this is not a property.

**Comment by XMalatji** [comment]
Try create your own custom directive and use the Host listener ato achieve this behavior.

**Comment by anasAsh** [comment]
I know that's too late, but it would be great if you have a sample repo where i can reproduce this, Am planing to do some upgrades on this package next week.
Thanks.

**Comment by XMalatji** [comment]
Hey man no sweat. Had to devise my own ways.

Phaseka Malatji
*Multimedia Developer*

Cell:  +27 (0)73 542 3212
Email: phasekamalatji@gmail.com

**Comment by zxjQAZ** [comment]
I meet the same problem ,need you opgrade the package !!
