### ISSUE TITLE
not compatible with angular 6

### ISSUE THREAD

**Issue by ritsrivastava01** [anasAsh/ngx-scroll-event#11]
HI Developers,
 I'm trying to move my application from Angular 5 to 6, but while upgrading its throwing 5 errors related to peer dependencies.

Pls, let me know how can I fix those issue?

**Comment by anasAsh** [comment]
Hi, I will be available to work on upgrading this package next week, if you feel like fixing it, you can re-check the dependencies in `packages.json` and create a PR, I will be happy to merge this.

**Comment by anasAsh** [comment]
Fixed.
