### ISSUE TITLE
Angular v10, Trouble importing into App.Module

### ISSUE THREAD

**Issue by cdo-tesseract** [anasAsh/ngx-scroll-event#20]
Module '"../../node_modules/ngx-scroll-event/ngx-scroll-event"' has no exported member 'ScrollEventModule'.ts(2305)

**Comment by anasAsh** [comment]
documentation issues, it should be `NgxScrollEventModule`, will fix the readme file in a bit

**Comment by anasAsh** [comment]
Updated, Thanks for reporting 👍
