### ISSUE TITLE
exported modules changed

### ISSUE THREAD

**Issue by coanpape** [anasAsh/ngx-scroll-event#21]
Hello,   
Thank you for the recent & well timed update to this package.  I just noted that the previous method of importing this library:
import { ScrollEventModule } from 'ngx-scroll-event';
no longer works and so went into the library metadata to find the exported equivalent is apparently now "NgxScrollEventModule".
The readMe still features the old name.
Thank you

**Comment by anasAsh** [comment]
sorry for not responding earlier, I will fix it soon :D

**Comment by anasAsh** [comment]
fixed in 2.0.1, Thanks :D
