### ISSUE TITLE
Limit events

### ISSUE THREAD

**Issue by mirisbowring** [anasAsh/ngx-scroll-event#22]
Hi,

first of all, Thank you for this module!

**Situation:**
I pull some items from an api and display them as a grid.
When i scroll down, it fetches the next item page from the api and appends it to the rendered data.

**Problem:**
When scrolling, the "reachingBottom"/"reachingTop" event get's emitted multiple times.
This causes to do the same API call multiple times that causes me to display item pages multiple times.

**Example:**
```
+--------------------+
Item 1
Item 2
Item 3
+--------------------+
Item 4
Item 5
```
Item 1-3 are in my Viewport and item 4/5 are my "buffer"
When scrolling down, the event gets emitted and calls my api:
```
...get("/page&after=5")
```
Since the events gets emitted faster than my api responds, the request will be send multiple times and my list looks like this:
```
Item 1
Item 2
Item 3
+--------------------+
Item 4
Item 5
Item 6
Item 7
+---------------------+
Item 8
Item 6
Item 7
Item 8
Item 6
Item 7
Item 8
```

**Feature Request:**
I would like to have an ability to limit the amount of events or "lock" them until unlocked.

Regards

**Comment by anasAsh** [comment]
Hey there, sorry for the late reply, I think what you are looking for is to throttle events callback execution, I don't think this is something that we need to add to this package for you to have it.
I suggest to build that around the events coming out of this package, maybe this could help
https://medium.com/leantaas-engineering/throttling-api-calls-in-angular-64b8c0e0e137

**Comment by mirisbowring** [comment]
Thank you!

I'll implement this into my project. Thanks for your response.
