### ISSUE TITLE
isWindowEvent is always true, even if called from template elements

### ISSUE THREAD

**Issue by llakewood** [anasAsh/ngx-scroll-event#7]
Hello, I've implemented the code as the documentation instructs, even using the div blah blah blah example in the documentation, the isWindowEvent is always true despite being called from an element.

The only difference I see is that I'm using `templateUrl`, not the `template` as suggested in the documentation. Any ideas?

Thank you for your work!

**Comment by anasAsh** [comment]
Hey there, do you have a reproducible example? also, which browser are you checking on? any other details would be appreciated :)
